- pkg:pypi/configs@0.1
- pkg:pypi/configs@0.2
- pkg:pypi/configs@0.3
- pkg:pypi/configs@0.4
- pkg:pypi/configs@0.5
- pkg:pypi/configs@0.6
- pkg:pypi/configs@0.7
- pkg:pypi/configs@0.8
- pkg:pypi/configs@0.9
- pkg:pypi/configs@1.0
- pkg:pypi/configs@1.1
- pkg:pypi/configs@1.2
- pkg:pypi/configs@1.3
- pkg:pypi/configs@1.4
- pkg:pypi/configs@1.5
- pkg:pypi/configs@1.6
- pkg:pypi/configs@1.7
- pkg:pypi/configs@1.8
- pkg:pypi/configs@1.8.1
- pkg:pypi/configs@1.8.2
- pkg:pypi/configs@1.9.5
- pkg:pypi/configs@2.0.1
- pkg:pypi/configs@2.0.2
- pkg:pypi/configs@2.0.3
- pkg:pypi/configs@2.0.4
- pkg:pypi/configs@2.0.5
- pkg:pypi/configs@2.0.6
- pkg:pypi/configs@2.0.7
- pkg:pypi/configs@2.0.8
- pkg:pypi/configs@2.0.9
- pkg:pypi/configs@3.0.1
- pkg:pypi/configs@3.0.2
- pkg:pypi/configs@3.0.3
