- pkg:pypi/celery-prometheus-exporter@1.0.0
- pkg:pypi/celery-prometheus-exporter@1.0.1
- pkg:pypi/celery-prometheus-exporter@1.1.0
- pkg:pypi/celery-prometheus-exporter@1.2.0
- pkg:pypi/celery-prometheus-exporter@1.3.0
- pkg:pypi/celery-prometheus-exporter@1.4.0
- pkg:pypi/celery-prometheus-exporter@1.5.0
- pkg:pypi/celery-prometheus-exporter@1.6.0
- pkg:pypi/celery-prometheus-exporter@1.7.0
