- pkg:pypi/celery-prometheus@0.1.0
- pkg:pypi/celery-prometheus@0.1.1
- pkg:pypi/celery-prometheus@0.2.0
- pkg:pypi/celery-prometheus@0.2.1
- pkg:pypi/celery-prometheus@1.0.0
- pkg:pypi/celery-prometheus@1.0.1
- pkg:pypi/celery-prometheus@1.1.0
