- pkg:pypi/celery-redis-prometheus@1.0.0
- pkg:pypi/celery-redis-prometheus@1.1.0
- pkg:pypi/celery-redis-prometheus@1.1.1
- pkg:pypi/celery-redis-prometheus@1.2.0
- pkg:pypi/celery-redis-prometheus@1.3.0
- pkg:pypi/celery-redis-prometheus@1.4.0
- pkg:pypi/celery-redis-prometheus@1.5.0
- pkg:pypi/celery-redis-prometheus@1.5.1
